export const consultantsData = [
    {
        id: 1,
        name: "دکتر نرگس صادقی",
        gender: "خانم",
        service: { type: "آنلاین", location: "-" },
        scientificDegree: "دکتری",
        specialty: "روان‌درمانگر کودک و نوجوان",
        bio: "بیش از ۱۰ سال تجربه در درمان مشکلات رفتاری کودکان و نوجوانان.",
        avatar: "https://randomuser.me/api/portraits/women/42.jpg",
        rating: 4.8,
        reviewsCount: 120,
        sessionsDone: 340,
        price: 250000,
    },
    {
        id: 2,
        name: "دکتر محمد رضایی",
        gender: "آقا",
        service: { type: "آنلاین", location: "تهران" },
        scientificDegree: "دکتری",
        specialty: "مشاور خانواده و ازدواج",
        bio: "تمرکز بر بهبود روابط زوج‌ها و حل تعارض‌های خانوادگی.",
        avatar: "https://randomuser.me/api/portraits/men/12.jpg",
        rating: 4.6,
        reviewsCount: 95,
        sessionsDone: 280,
        price: 220000,
    },
    {
        id: 3,
        name: "دکتر زهرا احمدی",
        gender: "خانم",
        service: { type: "آنلاین", location: "مشهد" },
        scientificDegree: "کارشناسی ارشد",
        specialty: "درمان اضطراب و افسردگی",
        bio: "متخصص در تکنیک‌های CBT و درمان مبتنی بر ذهن‌آگاهی.",
        avatar: "https://randomuser.me/api/portraits/women/10.jpg",
        rating: 4.9,
        reviewsCount: 150,
        sessionsDone: 410,
        price: 300000,
    },
    {
        id: 4,
        name: "دکتر علی کرمی",
        gender: "آقا",
        service: { type: "آنلاین", location: "شیراز" },
        scientificDegree: "کارشناس",
        specialty: "روان‌شناس عمومی",
        bio: "ارائه خدمات مشاوره فردی و گروهی برای نوجوانان و بزرگسالان.",
        avatar: "https://randomuser.me/api/portraits/men/42.jpg",
        rating: 4.7,
        reviewsCount: 85,
        sessionsDone: 200,
        price: 200000,
    },
    {
        id: 5,
        name: "دکتر مهسا سلیمانی",
        gender: "خانم",
        service: { type: "آنلاین", location: "-" },
        scientificDegree: "کارشناسی ارشد",
        specialty: "مشاوره پیش از ازدواج",
        bio: "راهنمایی تخصصی برای تصمیم‌گیری‌های قبل از ازدواج.",
        avatar: "https://randomuser.me/api/portraits/women/50.jpg",
        rating: 4.5,
        reviewsCount: 110,
        sessionsDone: 260,
        price: 240000,
    },
    {
        id: 6,
        name: "دکتر امیر سام نادری",
        gender: "آقا",
        service: { type: "آنلاین", location: "تهران" },
        scientificDegree: "کارشناس",
        specialty: "مشاوره شغلی و تحصیلی",
        bio: "تجربه در کمک به نوجوانان برای برنامه‌ریزی تحصیلی و شغلی.",
        avatar: "https://randomuser.me/api/portraits/men/30.jpg",
        rating: 4.4,
        reviewsCount: 70,
        sessionsDone: 150,
        price: 180000,
    },
    {
        id: 7,
        name: "دکتر سارا افشار",
        gender: "خانم",
        service: { type: "آنلاین", location: "شیراز" },
        scientificDegree: "دکتری",
        specialty: "درمان وسواس و اضطراب",
        bio: "استفاده از تکنیک‌های ACT و ERP در درمان وسواس.",
        avatar: "https://randomuser.me/api/portraits/women/45.jpg",
        rating: 4.9,
        reviewsCount: 130,
        sessionsDone: 320,
        price: 270000,
    },
    {
        id: 8,
        name: "دکتر مهدی شریفی",
        gender: "آقا",
        service: { type: "آنلاین", location: "تهران" },
        scientificDegree: "کارشناسی ارشد",
        specialty: "درمان اختلالات خواب",
        bio: "رویکرد رفتاری-شناختی برای رفع مشکلات خواب.",
        avatar: "https://randomuser.me/api/portraits/men/25.jpg",
        rating: 4.3,
        reviewsCount: 65,
        sessionsDone: 140,
        price: 210000,
    },
    {
        id: 9,
        name: "دکتر نیلوفر پارسایی",
        gender: "خانم",
        service: { type: "آنلاین", location: "تهران" },
        scientificDegree: "کارشناس",
        specialty: "مشاوره نوجوان",
        bio: "کمک به نوجوانان در مدیریت بحران‌های هویتی و تحصیلی.",
        avatar: "https://randomuser.me/api/portraits/women/33.jpg",
        rating: 4.6,
        reviewsCount: 90,
        sessionsDone: 180,
        price: 200000,
    },
    {
        id: 10,
        name: "دکتر رضا طاهری",
        gender: "آقا",
        service: { type: "آنلاین", location: "تهران" },
        scientificDegree: "دکتری",
        specialty: "روانشناسی مثبت‌گرا",
        bio: "تمرکز بر رشد فردی، شکرگزاری و معنای زندگی.",
        avatar: "https://randomuser.me/api/portraits/men/35.jpg",
        rating: 4.8,
        reviewsCount: 105,
        sessionsDone: 300,
        price: 260000,
    },
    {
        id: 11,
        name: "دکتر فرنوش نادری",
        gender: "خانم",
        service: { type: "آنلاین", location: "مشهد" },
        scientificDegree: "کارشناسی ارشد",
        specialty: "مشاوره فردی و خودشناسی",
        bio: "کمک به افزایش عزت نفس و رشد فردی.",
        avatar: "https://randomuser.me/api/portraits/women/52.jpg",
        rating: 4.7,
        reviewsCount: 115,
        sessionsDone: 250,
        price: 230000,
    },
    {
        id: 12,
        name: "دکتر حسین قادری",
        gender: "آقا",
        service: { type: "آنلاین", location: "-" },
        scientificDegree: "کارشناس",
        specialty: "درمان افسردگی مزمن",
        bio: "کار با رویکرد درمان پذیرش و تعهد (ACT) در افسردگی‌های مزمن.",
        avatar: "https://randomuser.me/api/portraits/men/45.jpg",
        rating: 4.4,
        reviewsCount: 60,
        sessionsDone: 130,
        price: 190000,
    },
    {
        id: 13,
        name: "دکتر الناز موسوی",
        gender: "خانم",
        service: { type: "آنلاین", location: "تهران" },
        scientificDegree: "کارشناسی ارشد",
        specialty: "مشاوره کودکان بیش‌فعال",
        bio: "کار با والدین و کودکان دارای ADHD.",
        avatar: "https://randomuser.me/api/portraits/women/19.jpg",
        rating: 4.6,
        reviewsCount: 100,
        sessionsDone: 220,
        price: 220000,
    },
    {
        id: 14,
        name: "دکتر میلاد کریمی",
        gender: "آقا",
        service: { type: "آنلاین", location: "تهران" },
        scientificDegree: "دکتری",
        specialty: "درمان وسواس‌های فکری",
        bio: "رویکرد شناختی رفتاری در درمان وسواس فکری و عملی.",
        avatar: "https://randomuser.me/api/portraits/men/39.jpg",
        rating: 4.9,
        reviewsCount: 145,
        sessionsDone: 370,
        price: 290000,
    }
];
