import gardnerImage from "../assets/images/banner/gardner.png"

export const examsData = [
    {
        id: 1,
        title: "آزمون هوش کودکان",
        description: "یک آزمون جامع برای سنجش هوش کودکان",
        image: gardnerImage,
        time: "30",
        participants: 128,
        questionsCount: 40,
        badge: "ویژه والدین",
        category: "شخصیت شناسی",
        price: "1000000",
        rating: "1"
    },
    {
        id: 2,
        title: "آزمون استعدادسنجی نوجوانان",
        description: "ارزیابی استعدادهای مختلف نوجوانان",
        image: gardnerImage,
        time: "45",
        participants: 90,
        questionsCount: 50,
        badge: "ویژه فرزندان",
        category: "شخصیت شناسی",
        price: "2000000",
        rating: "4"
    },
    {
        id: 3,
        title: "آزمون ترکیبی خانواده",
        description: "آزمونی برای والدین و فرزندان به صورت مشترک",
        image: gardnerImage,
        time: "60",
        participants: 150,
        questionsCount: 60,
        badge: "ویژه والدین و فرزندان",
        category: "خانواده",
        price: "1100000",
        rating: "3"
    },
    {
        id: 4,
        title: "آزمون هوش کودکان",
        description: "یک آزمون جامع برای سنجش هوش کودکان",
        image: gardnerImage,
        time: "30",
        participants: 120,
        questionsCount: 40,
        badge: "ویژه والدین",
        category: "سبک زندگی",
        price: "4500000",
        rating: "4"
    },
    {
        id: 5,
        title: "آزمون استعدادسنجی نوجوانان",
        description: "ارزیابی استعدادهای مختلف نوجوانان",
        image: gardnerImage,
        time: "45",
        participants: 92,
        questionsCount: 50,
        badge: "ویژه فرزندان",
        category: "اضطراب",
        price: "100",
        rating: "5"
    },
    {
        id: 6,
        title: "آزمون ترکیبی خانواده",
        description: "آزمونی برای والدین و فرزندان به صورت مشترک",
        image: gardnerImage,
        time: "60",
        participants: 150,
        questionsCount: 60,
        badge: "ویژه والدین و فرزندان",
        category: "اختلالات رفتاری",
        price: "250",
        rating: "2"
    },
    {id: 7,
        title: "2 آزمون هوش کودکان",
        description: "یک آزمون جامع برای سنجش هوش کودکان",
        image: gardnerImage,
        time: "30",
        participants: 184,
        questionsCount: 40,
        badge: "ویژه والدین",
        category: "شخصیت شناسی",
        price: "1250000",
        rating: "4"
    },
    {
        id: 8,
        title: " 2 آزمون استعدادسنجی نوجوانان",
        description: "ارزیابی استعدادهای مختلف نوجوانان",
        image: gardnerImage,
        time: "45",
        participants: 164,
        questionsCount: 50,
        badge: "ویژه فرزندان",
        category: "شخصیت شناسی",
        price: "2840000",
        rating: "4.5"
    },
    {
        id: 9,
        title: "2 آزمون ترکیبی خانواده",
        description: "آزمونی برای والدین و فرزندان به صورت مشترک",
        image: gardnerImage,
        time: "60",
        participants: 134,
        questionsCount: 60,
        badge: "ویژه والدین و فرزندان",
        category: "خانواده",
        price: "1580000",
        rating: "1.3"
    },
    {
        id: 10,
        title: "3 آزمون هوش کودکان",
        description: "یک آزمون جامع برای سنجش هوش کودکان",
        image: gardnerImage,
        time: "30",
        participants: 170,
        questionsCount: 40,
        badge: "ویژه والدین",
        category: "سبک زندگی",
        price: "4565000",
        rating: "2.5"
    },
    {
        id: 11,
        title: "2 آزمون استعدادسنجی نوجوانان",
        description: "ارزیابی استعدادهای مختلف نوجوانان",
        image: gardnerImage,
        time: "45",
        participants: 50,
        questionsCount: 50,
        badge: "ویژه فرزندان",
        category: "اضطراب",
        price: "1560000",
        rating: "2.9"
    },
    {
        id: 12,
        title: "2 آزمون ترکیبی خانواده",
        description: "آزمونی برای والدین و فرزندان به صورت مشترک",
        image: gardnerImage,
        time: "60",
        participants: 211,
        questionsCount: 60,
        badge: "ویژه والدین و فرزندان",
        category: "اختلالات رفتاری",
        price: "350000000",
        rating: "4.6"
    },
    {
        id: 13,
        title: "3 آزمون ترکیبی خانواده",
        description: "آزمونی برای والدین و فرزندان به صورت مشترک",
        image: gardnerImage,
        time: "60",
        participants: 281,
        questionsCount: 60,
        badge: "ویژه والدین و فرزندان",
        category: "اختلالات رفتاری",
        price: "45000000",
        rating: "3.4"
    },
    {
        id: 14,
        title: "4 آزمون ترکیبی خانواده",
        description: "آزمونی برای والدین و فرزندان به صورت مشترک",
        image: gardnerImage,
        time: "60",
        participants: 241,
        questionsCount: 60,
        badge: "ویژه والدین و فرزندان",
        category: "اختلالات رفتاری",
        price: "45000000",
        rating: "3.4"
    },
];